# Generated by Django 4.2.13 on 2024-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('is_install', models.BooleanField(default=False, verbose_name='安装状态')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否使用')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认版本')),
            ],
        ),
    ]
